<a href="https://colab.research.google.com/github/Sourav96S/Sourav96S/blob/main/matrix_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [3]:
import numpy as np



tensor_2d = np.array([(1,2,3),(3,4,5),(5,6,7)])

print(tensor_2d)

tensor_2d[2]

tensor_2d[2][2]

import tensorflow as tf

import numpy as np


matrix_1 = np.array([(1,2,3),(2,3,4),(3,2,1)],dtype='int32')

print(matrix_1)

matrix_2 = np.array([(1,1,1),(1,1,1),(1,1,1)],dtype='int32')

print(matrix_2)

matrix_1 = tf.constant(matrix_1)

print(matrix_1)

matrix_2 = tf.constant(matrix_2)

print(matrix_2)

matrix_product = tf.matmul(matrix_1,matrix_2)

print(matrix_product)



[[1 2 3]
 [3 4 5]
 [5 6 7]]
[[1 2 3]
 [2 3 4]
 [3 2 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
tf.Tensor(
[[1 2 3]
 [2 3 4]
 [3 2 1]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[6 6 6]
 [9 9 9]
 [6 6 6]], shape=(3, 3), dtype=int32)


In [4]:
matrix_add = tf.add(matrix_1,matrix_2)
matrix_add = tf.add(matrix_1,matrix_2)
print(matrix_add)

tf.Tensor(
[[2 3 4]
 [3 4 5]
 [4 3 2]], shape=(3, 3), dtype=int32)
